const assert = require("assert"), M = require("../Model.js")
const s = M.parseSample("mem_total=16000000\nmem_avail=4000000\nswap_used=2048\nvram_used=3000\nvram_total=6000\ngpu_util=40\ngpu_temp=55\nstate=active\nhealth=ok\nserver_rss=1048576\ntps=39.5")
assert.equal(s.ramPct, 75); assert.equal(s.vramPct, 50); assert.equal(s.ready, true)
assert.equal(s.serverRssMb, 1024); assert.equal(s.tps, 39.5); assert.equal(M.statusText(s), "Running · ready")
assert.equal(M.statusText(M.parseSample("state=inactive")), "Stopped")
assert.equal(M.push(new Array(60).fill(1), 2).length, 60)
console.log("ok")
const m = M.modelRow("/h/models/qwen2.5-coder-7b-instruct-q4_k_m.gguf", 4683073536)
assert.equal(m.quant, "Q4_K_M"); assert.equal(m.params, "7B"); assert.equal(m.name, "qwen2.5-coder-7b-instruct"); assert.equal(m.sizeMb, 4466)
assert.equal(M.fitVerdict(4466, 6141).level, 0); assert.equal(M.fitVerdict(8500, 6141).level, 1); assert.equal(M.fitVerdict(20000, 6141).level, 2)
const rows = M.parseModels("1048576|/home/u/models/b-7b-q8_0.gguf\n2097152|/home/u/.cache/huggingface/hub/x/a-3b-q4_k_m.gguf\n", "/home/u")
assert.equal(rows.length, 2); assert.equal(rows[0].name, "a-3b"); assert.equal(rows[0].source, "Hugging Face cache")
assert.equal(rows[0].deletable, false); assert.equal(rows[1].deletable, true); assert.equal(rows[1].source, "~/models")
assert.equal(M.fmtUptime(3725), "1h 2m"); assert.equal(M.ctxLabel(16384), "16k")
console.log("ok2")
const s2 = M.parseSample("cfg_PORT=9090\ncfg_NGL=0\ncfg_KV=-ctk q8_0 -ctv q8_0\ncfg_AUTOSTOP=15\nenabled=enabled\nadded=/a/x.gguf\nadded=/b\nbusy=1")
assert.equal(s2.port, 9090); assert.equal(s2.ngl, 0); assert.equal(s2.compactKv, true); assert.equal(s2.autoStopMin, 15)
assert.equal(s2.atLogin, true); assert.deepEqual(s2.added, ["/a/x.gguf", "/b"]); assert.equal(s2.busy, true)
assert.equal(M.validPort("8080"), true); assert.equal(M.validPort("80"), false); assert.equal(M.validPort("80a"), false)
assert.equal(JSON.parse(M.zedConfig(9090, "m")).language_models.openai_compatible["llama.cpp"].api_url, "http://localhost:9090/v1")
console.log("ok3")
const fr = M.parseModels("1|/home/u/models/qwen-7b-q4_k_m.gguf\n1|/home/u/models/llama-3b-q8_0.gguf\n", "/home/u")
assert.equal(M.filterModels(fr, "").length, 2); assert.equal(M.filterModels(fr, "QWEN q4").length, 1)
assert.equal(M.filterModels(fr, "3b").length, 1); assert.equal(M.filterModels(fr, "zzz").length, 0)
console.log("ok4")
assert.equal(M.activeFirst(fr, "/home/u/models/qwen-7b-q4_k_m.gguf")[0].name, "qwen-7b"); assert.equal(M.activeFirst(fr, "")[0].name, "llama-3b")
console.log("ok5")
assert.equal(M.gb(30), "30 MB"); assert.equal(M.gb(4466), "4.4 GB")
console.log("ok6")

// --- GPU kinds and onboarding
const nv = M.parseSample("gpu_kind=nvidia\ngpu_integrated=0\nvram_used=3000\nvram_total=6000\ngpu_util=10\ngpu_temp=60\nmem_total=16000000")
assert.equal(M.gpuText(nv), "10%  ·  60°C"); assert.equal(M.memHeading(nv), "VRAM"); assert.equal(M.fitFor(4466, Object.assign({}, nv, { vramTotalMb: 6141 })).level, 0)
const ig = M.parseSample("gpu_kind=intel\ngpu_integrated=1\ngpu_util=-1\ngpu_temp=0\nmem_total=16000000\nserver_rss=1048576")
assert.equal(ig.integrated, true); assert.equal(M.gpuText(ig), "n/a"); assert.equal(M.memHeading(ig), "Shared memory")
assert.equal(ig.vramTotalMb, 15625); assert.equal(ig.vramUsedMb, 1024); assert.equal(M.fitFor(4466, ig).text, "Fits shared RAM")
assert.equal(M.fitFor(9000, Object.assign({}, ig, { ramTotalMb: 8000 })).level, 2)
const cpu = M.parseSample("gpu_kind=none\nmem_total=8000000")
assert.equal(M.gpuText(cpu), "no GPU"); assert.equal(M.gpuHeading(cpu), "CPU"); assert.equal(M.fitFor(1000, cpu).text, "CPU only")
const doc = M.parseDoctor("bin=/x/llama-server\nbin_version=0.6\ndevices=cuda\ngpu_kind=nvidia\ngpu_name=NVIDIA RTX\nunit=installed\nmissing_tools=wl-copy,wl-paste,python-gi")
assert.equal(M.needsSetup(doc), false); assert.equal(M.accelerated(doc), true)
assert.equal(M.accelerated(Object.assign({}, doc, { devices: [] })), false)
assert.equal(M.needsSetup(Object.assign({}, doc, { bin: "" })), true); assert.equal(M.needsSetup(M.EMPTY_DOCTOR), false)
assert.equal(M.accelerated({ gpuKind: "intel", devices: ["vulkan"] }), true); assert.equal(M.accelerated({ gpuKind: "none", devices: [] }), true)
assert.ok(/no CUDA support/.test(M.deviceSummary(Object.assign({}, doc, { devices: ["cpu"] }))))
assert.ok(/CUDA$/.test(M.deviceSummary(doc)))
assert.ok(/GGML_CUDA=ON/.test(M.buildCommand("nvidia"))); assert.ok(/GGML_VULKAN=ON/.test(M.buildCommand("intel"))); assert.ok(!/GGML_/.test(M.buildCommand("none")))
assert.ok(/7b/.test(M.starterModel(6141).command)); assert.ok(/3b/.test(M.starterModel(4000).command)); assert.ok(/1.5b/.test(M.starterModel(1000).command))
assert.deepEqual(M.missingPackages(doc.missing), ["wl-clipboard", "python-gobject"])
console.log("ok7")
